# Site settings
title: Matt Lucas | Senior Email Developer
description: "Charlotte, North Carolina HTML Email Developer"
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://mattdavidlucas.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  style: compressed
env: production
