# Site settings
title: Matt Lucas | Front End Developer & Digital Marketer
description: San Francisco Bay Area developer with a focus on digital marketing.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://mattdavidlucas.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  style: compressed
