# Site settings
title: Matt Lucas
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mattdavidlucas.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  style: compressed
env: production
