# Site settings
title: Matt Lucas
email: mattdavidlucas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  San Francisco Bay Area developer with a focus on digital marketing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mattdavidlucas.com" # the base hostname & protocol for your site
twitter_username: mattdavidlucas
github_username:  mattdavidlucas

# Build settings
markdown: kramdown
